export const mockDatas = [
  {
    id: 1,
    name: "name1",
    category: "category1",
    url: "www.website1.com",
    username: "user1",
    password: "password1",
  },
  {
    id: 2,
    name: "name2",
    category: "category2",
    url: "www.url2.com",
    username: "user2",
    password: "password2",
  },
  {
    id: 3,
    name: "name3",
    category: "category3",
    url: "www.url3.com",
    username: "user3",
    password: "password3",
  },
  {
    id: 4,
    name: "name4",
    category: "category4",
    url: "www.url4.com",
    username: "user4",
    password: "password4",
  },
  {
    id: 5,
    name: "name5",
    category: "category5",
    url: "www.url5.com",
    username: "user5",
    password: "password5",
  },
  {
    id: 6,
    name: "name6",
    category: "category6",
    url: "www.url6.com",
    username: "user6",
    password: "password6",
  },
  {
    id: 7,
    name: "name7",
    category: "category7",
    url: "www.url7.com",
    username: "user7",
    password: "password7",
  },
  {
    id: 8,
    name: "name8",
    category: "category8",
    url: "www.url8.com",
    username: "user8",
    password: "password8",
  },
  {
    id: 9,
    name: "name9",
    category: "category9",
    url: "www.url9.com",
    username: "user9",
    password: "password9",
  },
  {
    id: 10,
    name: "name10",
    category: "category10",
    url: "www.url10.com",
    username: "user10",
    password: "password10",
  },
  {
    id: 11,
    name: "name11",
    category: "category11",
    url: "www.url11.com",
    username: "user11",
    password: "password11",
  },
  {
    id: 12,
    name: "name12",
    category: "category12",
    url: "www.url12.com",
    username: "user12",
    password: "password12",
  },
];
